# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-17 12:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0004_musiccluster'),
    ]

    operations = [
        migrations.AddField(
            model_name='musiccluster',
            name='aggressive',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='musiccluster',
            name='calm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='musiccluster',
            name='lively',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='musiccluster',
            name='peaceful',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='musiccluster',
            name='tense',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
