# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-05 06:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0005_emotionemotionbasedsong'),
    ]

    operations = [
        migrations.AddField(
            model_name='musiccluster',
            name='cluster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recommendation.Cluster'),
        ),
    ]
