# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-16 02:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0006_situationemotion'),
    ]

    operations = [
        migrations.AddField(
            model_name='emotionrelevantsong',
            name='situation',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
