# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-23 04:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0007_emotionrelevantsong_situation'),
    ]

    operations = [
        migrations.AddField(
            model_name='emotionemotionbasedsong',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 23, 13, 50, 4, 104517)),
        ),
        migrations.AddField(
            model_name='emotionemotionbasedsong',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 23, 13, 50, 4, 104545)),
        ),
        migrations.AddField(
            model_name='emotionrelevantsong',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 23, 13, 50, 4, 103639)),
        ),
        migrations.AddField(
            model_name='emotionrelevantsong',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 23, 13, 50, 4, 103672)),
        ),
    ]
