# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-23 06:14
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recommendation', '0008_auto_20161123_1350'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchSong',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('situation', models.IntegerField()),
                ('feedback_type', models.IntegerField()),
                ('created_at', models.DateTimeField(default=datetime.datetime(2016, 11, 23, 15, 14, 16, 684743))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2016, 11, 23, 15, 14, 16, 684776))),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommendation.Song')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='emotionemotionbasedsong',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 23, 15, 14, 16, 683130)),
        ),
        migrations.AlterField(
            model_name='emotionemotionbasedsong',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 23, 15, 14, 16, 683161)),
        ),
        migrations.AlterField(
            model_name='emotionrelevantsong',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 23, 15, 14, 16, 682174)),
        ),
        migrations.AlterField(
            model_name='emotionrelevantsong',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 23, 15, 14, 16, 682209)),
        ),
    ]
