# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-12-21 05:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0012_auto_20161220_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emotionemotionbasedsong',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2016, 12, 21, 14, 44, 47, 741355)),
        ),
        migrations.AlterField(
            model_name='emotionemotionbasedsong',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2016, 12, 21, 14, 44, 47, 741385)),
        ),
        migrations.AlterField(
            model_name='emotionrelevantsong',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2016, 12, 21, 14, 44, 47, 740562)),
        ),
        migrations.AlterField(
            model_name='emotionrelevantsong',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2016, 12, 21, 14, 44, 47, 740598)),
        ),
        migrations.AlterField(
            model_name='searchsong',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2016, 12, 21, 14, 44, 47, 743148)),
        ),
        migrations.AlterField(
            model_name='searchsong',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2016, 12, 21, 14, 44, 47, 743175)),
        ),
        migrations.AlterField(
            model_name='situationemotion',
            name='emotion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommendation.Tag'),
        ),
    ]
