# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-12-22 06:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0014_auto_20161222_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='search_flag',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='emotionemotionbasedsong',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2016, 12, 22, 15, 0, 31, 378427)),
        ),
        migrations.AlterField(
            model_name='emotionemotionbasedsong',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2016, 12, 22, 15, 0, 31, 378455)),
        ),
        migrations.AlterField(
            model_name='emotionrelevantsong',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2016, 12, 22, 15, 0, 31, 377615)),
        ),
        migrations.AlterField(
            model_name='emotionrelevantsong',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2016, 12, 22, 15, 0, 31, 377651)),
        ),
        migrations.AlterField(
            model_name='searchsong',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2016, 12, 22, 15, 0, 31, 380429)),
        ),
        migrations.AlterField(
            model_name='searchsong',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2016, 12, 22, 15, 0, 31, 380459)),
        ),
    ]
