# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-12-22 13:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0015_auto_20161222_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchtag',
            name='cluster',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='emotionemotionbasedsong',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2016, 12, 22, 22, 19, 5, 841195)),
        ),
        migrations.AlterField(
            model_name='emotionemotionbasedsong',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2016, 12, 22, 22, 19, 5, 841222)),
        ),
        migrations.AlterField(
            model_name='emotionrelevantsong',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2016, 12, 22, 22, 19, 5, 840270)),
        ),
        migrations.AlterField(
            model_name='emotionrelevantsong',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2016, 12, 22, 22, 19, 5, 840303)),
        ),
        migrations.AlterField(
            model_name='searchsong',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2016, 12, 22, 22, 19, 5, 843207)),
        ),
        migrations.AlterField(
            model_name='searchsong',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2016, 12, 22, 22, 19, 5, 843235)),
        ),
    ]
