# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-01-15 08:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0019_auto_20170106_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emotionemotionbasedsong',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 15, 17, 47, 4, 985945)),
        ),
        migrations.AlterField(
            model_name='emotionemotionbasedsong',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 15, 17, 47, 4, 985974)),
        ),
        migrations.AlterField(
            model_name='emotionrelevantsong',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 15, 17, 47, 4, 985133)),
        ),
        migrations.AlterField(
            model_name='emotionrelevantsong',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 15, 17, 47, 4, 985168)),
        ),
        migrations.AlterField(
            model_name='searchsong',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 15, 17, 47, 4, 987729)),
        ),
        migrations.AlterField(
            model_name='searchsong',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 15, 17, 47, 4, 987754)),
        ),
    ]
